import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    signInText: 'SIGN IN',
    justo: 'Justo',
    notificationHeader: 'Notification',
    dashboardHeader: 'Dashboard',
    registrationHeader: 'Registration',
    companyDetails: 'Company Information',
    registernow: 'register now',
    propertyHeader: 'Property',
    propertyManagementHeader: 'Property Management',
    closingManagerHeader: 'Closing Manager',
    appointmentHeader: 'Appointment',
    readytoBookHeader: 'Ready to Book',
    bookingRequestHead: 'Booking Request',
    recoveryHeader: 'Recovery',
    saleToolHeader: 'Sales tools',
    agencyHeader: 'Agency(CP)',
    leadManagementHeader: 'Lead Management',
    appointmentWithCPHeader: 'Appointment With CP',
    appointmentForVisitHeader: 'Appointment For Site Visit',
    reportHeader: 'Report',
    chatHeader: 'Chat',
    supportHeader: 'Support',
    supportForumHeader: 'Support Forum',
    leaderBoardHeader: 'LeaderBoard',
    bookingListHeader: 'Booking List',
    settingHeader: 'Setting',
    logout: 'LogOut',
    versionText: 'version',
    forgotPassword: 'Forgot Password?',
    newUserText: 'New User?',
    signUp: 'Sign Up',
    byCreating: 'By Signing up you agree to our',
    termsAndCondition: 'Terms & Conditions',
    and: 'and',
    view: 'View',
    status: 'Status',
    privacyPolicy: 'Privacy Policy',
    ofJusto: 'of Justo.',
    basicInfoText: 'Basic Information',
    allocate: 'Allocate',
    propertyDetailHeader: 'Property Detail',
    searchProperty: 'Search Property',
    resend: 'Resend',
    notRecived: `Didn't receive the code?`,
    codeSent: 'A verification code has been sent to',
    your: ' your',
    email: 'email address',
    otpVerification: 'OTP VERIFICATION',
    imagecontentHeader: 'Images',
    cameraHeader: 'Camera',
    galleryHeader: 'Gallery',
    videocontentHeader: 'Videos',
    cataloguecontentHeader: 'Catalogue',
    createVisit: 'CREATE VISIT',
    gender: "Gender :",
    male: "Male",
    female: "Female",
    next: 'next',
    listOfall: 'List of all',
    addnewagent: 'Add new Agent',
    agentdetail: 'Agent Detail',
    logInText: 'LOG IN',
    dontHaveAnAcc: `Don't Have an account?`,
    registerNow: 'Register Now',
    setting: "Setting",
    userRole: "USER ROLE",
    channelPartner: 'CHANNEL PARTNER',
    updateProfile: 'UPDATE PROFILE',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    changeLink: 'Change Link',
    copyLink: 'Copy Link',
    dropLocation: 'Drop Location',
    selectNewCloseManager: 'Select New Closing Manager',


    // common strings
    search: 'Search',
    update: 'Update',
    searchbytype: 'Search By Tpe',
    call: 'Call',
    unsubscribe: 'Unsubscribe',
    subscribe: 'Subscribe',

    /**Confirm Model**/
    ConfirmationModalTxt: 'Select the reason for\r\nunsubscribe this property.',
    Confirm: 'Confirm',

    /*** Sourcing Managers ***/
    SourcingManagersHeader: 'Sourcing Managers',
    addNewSM: 'Add New SM',
    allocateCp: 'Allocate CP',
    createSM: 'Create SM',
    editSM: 'Edit SM',
    updateSM: 'Update SM',
    cpAllocation: 'CP Allocation',
    newAllocateTxt: 'Allocate to New CP',
    noCpSelected: 'No CP Selected',
    selectMonth: 'Select Month',
    startDate: "Start Date",
    endDate: "End Date",
    visitTarget: "Visit target",
    siteVisitTarget: "Site visit target",
    closeTarget: "Close target",
    addTarget: "Add target",
    SMDetails: "SM Detail",
    selectSM: "Select SM",
    transferToAllVisitor: 'for transfer to all visitors of',

    /*** agency ***/
    addnewAgency: 'Add new Agency',
    pendingconfirm: 'Pending Confirm',
    edit: 'Edit',
    deactive: 'Deactive',
    Agencydetail: 'Agency Detail',
    userbankinfo: 'User Bank Info',
    createnewagency: 'Create New Agency',
    confirmation: 'Confirmation',
    active: 'Active',
    searchAgency: 'Search Agency',
    apply: 'Apply',
    no: 'No',
    yes: 'Yes',
    agent: 'Agent',
    createAgent: 'Create Agent',
    updatepassword: 'Update Password',
    deactivconfirmation: 'Are You sure you want to Deactive this',

    // All Leads
    visitor: 'Visitor',
    bulkupload: 'Bulk Upload',
    uploadCSV: 'Upload CSV',
    uploadimage: 'Upload Image',
    addnewvisitor: 'Add New Visitor',
    editVisitor: 'Update Visitor',
    visitordetails: 'Visitor Details',
    visitorAppointmentdetails: 'Visitor Appointment Details',
    searchvisitor: 'Search Visitor',
    propertyrequire: 'Property Require',
    createVisitor: 'Create Visitor',
    Statusupdate: 'Status Update',
    ScheduleSitevisite: 'Schedule Site Visite',
    createandschedule: 'Create & schedule',
    propertyrequired: 'Property Required',
    Customerdetails: 'Customer Details',
    companydetails: 'Company Details',
    configuration: 'Configuration',
    byvisitorscore: 'By Visitor Score',

    // Follow-Up
    followupHeader: 'Follow-up',
    followupDetails: 'Follow-Up Detail',
    searchfollowup: 'Search Follow-Up',
    allfollowup: 'All Followup',
    editfollowup: 'Edit Follow-Up',


    // Appointment
    appointmnet: 'Appointmnet',
    appointmnetdetail: 'Appointmnet Detail',
    updatestatus: 'Update Status',
    searchappointment: 'Search Appointment',
    addNewappointment: 'Add New Appointment',
    selectLead: 'Select Lead',
    selectproperty: 'Select Property',
    appointmentDate: 'Appointment Date',
    appointmentTime: 'Appointment Time',
    location: 'Location',
    noofguest: 'No. of Guest',
    pickupAppointment: 'PickUp(if add property time set yes)',
    appointmentType: 'Appointment Type',
    appointmentWith: 'Appointment With',
    doneappointment: 'Done Appointment',

    // Pickup request
    PickuprequestHeader: 'Pickup Request'
  },
});

export default strings;
