import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    signInText: 'SIGN IN',
    justo: 'Justo',
    notificationHeader: 'Notification',
    dashboardHeader: 'Dashboard',
    registrationHeader: 'Registration',
    companyDetails: 'Company Information',
    registernow: 'register now',
    propertyHeader: 'Property',
    propertyManagementHeader: 'Property Management',
    closingManagerHeader: 'Closing Manager',
    appointmentHeader: 'Appointment',
    readytoBookHeader: 'Ready to Book',
    bookingRequestHead: 'Booking Request',
    playVideo: 'Play',
    recoveryHeader: 'Recovery',
    saleToolHeader: 'Sales Tools',
    agencyHeader: 'CP Management',
    agencyDeactiveHeader: 'Agency Deactive',
    leadManagementHeader: 'Lead Management',
    appointmentWithCPHeader: 'Appointment With CP',
    appointmentForVisitHeader: 'Appointment For Site Visit',
    appointmentVisitHeader: 'Appointment Site Visit',
    reportHeader: 'Report',
    chatHeader: 'Chat',
    supportHeader: 'Raise Ticket',
    supportForumHeader: 'Support Forum',
    leaderBoardHeader: 'LeaderBoard',
    bookingListHeader: 'Booking List',
    bookingDetails: 'Booking Details',
    settingHeader: 'Setting',
    logout: 'Logout',
    versionText: 'version',
    forgotPassword: 'Forgot Password?',
    newUserText: 'New User?',
    signUp: 'Sign Up',
    byCreating: 'By Signing up you agree to our',
    termsAndCondition: 'Terms & Conditions',
    and: 'and',
    scanQrCode: 'Scan Qr',
    view: 'View',
    status: 'Status',
    cancel: 'Cancel',
    privacyPolicy: 'Privacy Policy',
    ofJusto: 'of Justo.',
    basicInfoText: 'Basic Information',
    allocate: 'Allocate',
    propertyDetailHeader: 'Property Detail',
    searchProperty: 'Search Property',
    resend: 'Resend',
    notRecived: `Didn't receive the code?`,
    codeSent: 'A verification code has been sent to',
    your: ' your',
    email: 'email address',
    otpVerification: 'OTP VERIFICATION',
    imagecontentHeader: 'Images',
    cameraHeader: 'Camera',
    galleryHeader: 'Gallery',
    videocontentHeader: 'Videos',
    cataloguecontentHeader: 'Catalogue',
    createVisit: 'CREATE VISIT',
    visits: 'Visits',
    gender: "Gender :",
    male: "Male",
    female: "Female",
    next: 'next',
    listOfall: 'List of all',
    addnewagent: 'Add new Agent',
    agentdetail: 'Agent Detail',
    logInText: 'LOG IN',
    dontHaveAnAcc: `Don't Have an account?`,
    registerNow: 'Register Now',
    setting: "Setting",
    userRole: "USER ROLE",
    channelPartner: 'CHANNEL PARTNER',
    updateProfile: 'UPDATE PROFILE',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    changeLink: 'Change Link',
    copyLink: 'Copy Link',
    dropLocation: 'Drop Location',
    selectNewCloseManager: 'Select New Closing Manager',
    bookNow: 'Book Now',
    browse: 'Browse',
    reset: 'RESET',
    transfer: 'transfer',
    comingSoon: 'Coming Soon',
    notification: 'Notification',
    decline: 'Decline',
    done: 'Done',


    usernamepasswordempty: 'Username and Password is require. Please enter Username and password',
    correctemail: 'Enter correct Email Address',
    usernamerequired: 'Username is require. Please enter username',
    passwordrequired: 'Password is require. Please enter password',
    emailrequired: 'Email is require. Please enter email',
    otprequired: 'Enter your OTP',
    passwordnotmatch: 'Password and Confirm Password not match !',
    requiredpassword: 'Enter your Password and Confirm Password',
    requiredField: 'All Password field are required',
    sendotp: 'Send OTP',
    registration: 'registration',
    followup: 'Follow-Up',


    // common strings
    search: 'Search',
    update: 'Update',
    searchbytype: 'Search By Type',
    call: 'Call',
    unsubscribe: 'Unsubscribe',
    subscribe: 'Subscribe',
    city: 'City',
    propertyChat: 'Property chat',
    user: 'User',

    /**Confirm Model**/
    ConfirmationModalTxt: 'Select the reason for\r\nunsubscribe this property.',
    Confirm: 'Confirm',

    /*** Sourcing Managers ***/
    SourcingManagersHeader: 'Sourcing Managers',
    addNewSM: 'Add New SM',
    allocateCp: 'Allocate CP',
    createSM: 'Create SM',
    editSM: 'Edit SM',
    updateSM: 'Update SM',
    cpAllocation: 'CP Allocation',
    allocation: 'Allocation',
    newAllocateTxt: 'Allocate to New CP',
    noCpSelected: 'No CP Selected',
    noCpFound: 'No CP Found',
    selectMonth: 'Select Month',
    startDate: "Start Date",
    endDate: "End Date",
    visitTarget: "Visit target",
    siteVisitTarget: "Site visit target",
    closeTarget: "Close target",
    addTarget: "Add target",
    SMDetails: "SM Detail",
    selectSM: "Select SM",
    transferToAllVisitor: 'for transfer to all visitors of',


    /*** Closing Managers ***/
    addNewCM: 'Add New CM',
    createCM: 'Create CM',
    editCM: 'Edit CM',
    updateCM: 'Update CM',
    cpAllocationCm: 'CP Allocation',
    CMDetails: "CM Detail",
    selectCM: "Select CM",

    /*** agency ***/
    addnewAgency: 'Add new CP',
    pendingconfirm: 'Approve New CP',
    AllocateRequest: 'Allocate Property to CP',
    edit: 'Edit',
    add: 'Add',
    confirm: 'Confirm',
    deactive: 'Deactive',
    Agencydetail: 'CP Detail',
    userbankinfo: 'User Bank Info',
    createnewagency: 'Create New Agency',
    editagency: 'Edit Agency',
    confirmation: 'Confirmation',
    active: 'Active',
    searchAgency: 'Search Agency',
    apply: 'Apply',
    transferVisit: 'Transfer Visit',
    no: 'No',
    yes: 'Yes',
    agency: 'Agency',
    createAgent: 'Create Agent',
    updatepassword: 'Update Password',
    deactivconfirmation: 'Are You sure you want to Deactive this',
    activeconfirmation: 'Are you sure you want to Active this',

    // All Leads
    visitor: 'Visitor',
    bulkupload: 'Bulk Upload',
    uploadCSV: 'Upload CSV',
    uploadimage: 'Upload Image',
    addnewvisitor: 'Add New Visitor',
    editVisitor: 'Update Visitor',
    visitordetails: 'Visitor Details',
    visitorAppointmentdetails: 'Visitor Appointment Details',
    searchvisitor: 'Search Visitor',
    selectAgency: 'Select Agency',
    propertyrequire: 'Property Require',
    createVisitor: 'Create Visitor',
    Statusupdate: 'Status Update',
    cancelBooking: 'Cancel Booking',
    ScheduleSitevisite: 'Schedule Site Visit',
    createandschedule: 'Create & schedule',
    propertyrequired: 'Property Required',
    Customerdetails: 'Customer Details',
    companydetails: 'Company Details',
    configuration: 'Configuration',
    byvisitorscore: 'By Visitor Score',

    // Follow-Up
    followupHeader: 'Follow-up',
    followupDetails: 'Follow-Up Detail',
    searchfollowup: 'Search Follow-Up',
    allfollowup: 'History',
    editfollowup: 'Edit Follow-Up',


    // Appointment
    appointmnet: 'Appointment',
    appointmnetdetail: 'Appointment Detail',
    updatestatus: 'Update Status',
    searchappointment: 'Search Appointment',
    addNewappointment: 'Add New Appointment',
    editNewappointment: 'Edit Appointment',
    selectLead: 'Select Lead',
    selectproperty: 'Select Property',
    reason: 'Reason',
    appointmentDate: 'Appointment Date',
    appointmentTime: 'Appointment Time',
    location: 'Location',
    noofguest: 'No. of Guest',
    pickupAppointment: 'PickUp',
    appointmentType: 'Appointment Type',
    appointmentWith: 'Appointment With',
    doneappointment: 'Done Appointment',
    visitorupdate: 'Visitor Update',
    viewfollowup: 'View Follow-Up',
    updateStatus: 'Update Status',

    // Pickup request
    PickuprequestHeader: 'Pickup Request',

    // PERMISSION
    txt_setting_heading_media: 'Justo Would Like to Access Your Photos',
    txt_setting_heading_camera: 'Justo Would Like to Access the Camera',
    txt_setting_heading_contact: 'Justo Would Like to Access Your Contacts',
    txt_setting_heading_location: 'Justo Would Like to Access Your location',
    txt_setting_heading_microPhone: 'Justo Would Like to Access Your MicroPhone',
    txt_setting_description_contact:
      'To allow this, tap Settings below and turn on Contacts.',
    txt_setting_description_microPhone:
      'To allow this, tap Settings below and turn on MicroPhone.',
    txt_setting_description_camera:
      'To allow, tap on Settings and turn on Camera.',
    txt_setting_description_location:
      'To allow, tap on Settings and turn on location.',
    txt_setting_description_media: 'To allow, tap on Settings and turn on Photos.',
    txt_setting_access:
      'Justo does not have access. To enable access, tap on Settings and turn on the permissions.',
    txt_setting_camera:
      'Justo does not have access to your camera. To enable access, tap on Settings and turn on Camera.',
    txt_setting_media:
      'Justo does not have access to your media. To enable access, tap on Settings and turn on Media.',
    txt_setting_media_camera:
      'Justo does not have access to your camera and media. To enable access, tap on Settings and turn on Camera and Media.',
    txt_setting_contact:
      'Justo does not have access to your contact. To enable access, tap on Settings and turn on Contacts.',
    txt_setting_Location:
      'Justo does not have access to your Location. To enable access, tap on Settings and turn on Location.',

    addLocation: 'Add Locations',
    notSelectedLocation: 'Not Selected Location',
    searchYourlocation: 'Search your location here',
    notfount: 'Not Found',
    ocupacion: 'Ocupacion',
  },
});

export default strings;
