export const ADD_USERS = 'ADD_USERS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_USERS = 'GET_USERS';
export const REGISTER_ADD_USERS = 'REGISTER_ADD_USERS';
export const REGISTER_ADD_ERROR = 'REGISTER_ADD_ERROR';
export const USERS_ERROR = 'USERS_ERROR'
export const TOKEN_GENRATE = 'TOKEN_GENRATE'
export const USER_LIST = 'USER_LIST'
export const USER_DETAIL = 'USER_DETAIL'
export const USER_FILTERDETAIL = 'USER_FILTERDETAIL'
export const EDIT_USER = 'EDIT_USER'
export const USERSTATUS_UPDATE = 'USERSTATUS_UPDATE'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_ERROR = 'FORGOT_ERROR'
export const FORGOT_NULL = 'FORGOT_NULL'
export const OTPVERIFY = 'OTPVERIFY'
export const OTPVERIFY_NULL = 'OTPVERIFY_NULL'
export const OTPVERIFY_ERROR = 'OTPVERIFY_ERROR'
export const RESENDOTP = 'RESENDOTP'
export const RESENDOTP_NULL = 'RESENDOTP_NULL'
export const RESENDOTP_ERROR = 'RESENDOTP_ERROR'
export const UPDATEPASSWORD = 'UPDATEPASSWORD'
export const UPDATEPASSWORD_ERROR = 'UPDATEPASSWORD_ERROR'
export const UPDATEPASSWORD_NULL = 'UPDATEPASSWORD_NULL'
export const CHANGEPASSWORD = 'CHANGEPASSWORD'
export const CHANGEPASSWORD_ERROR = 'CHANGEPASSWORD_ERROR'

// PROPERTY
export const PROPERTY_FORM = 'PROPERTY_FORM'
export const PROPERTY_FORM_UPDATE = 'PROPERTY_FORM_UPDATE'
export const ADD_PROPERTY = 'ADD_PROPERTY'
export const PROPERTY_LIST = 'PROPERTY_LIST'
export const PROPERTY_EDIT = 'PROPERTY_EDIT'
export const GETPROPERTY_DETAIL = 'GETPROPERTY_DETAIL'
export const PROPERTY_FILTER_LIST = 'PROPERTY_FILTER_LIST'
export const PROPERTY_STATUS_UPDATE = 'PROPERTY_STATUS_UPDATE'
export const PROPERTY_ERROR = 'PROPERTY_ERROR'
export const SOURCING_MANAGER_LIST = 'SOURCING_MANAGER_LIST'
export const ALLOCATE_PROPERTY_TO_USER = 'ALLOCATE_PROPERTY_TO_USER'




// MASTER
export const CREATE_MASTER = 'CREATE_MASTER'
export const GET_AMENITY = 'GET_AMENITY'
export const GET_CONFIGURATION = 'GET_CONFIGURATION'
export const GET_PROPERTY_TYPE = 'GET_PROPERTY_TYPE'
export const GET_INSENTIVE_TYPE = 'GET_INSENTIVE_TYPE'
export const MASTER_LIST = 'MASTER_LIST'
export const MASTER_ERROR = 'MASTER_ERROR'
export const GET_SOURCING_MANAGER = 'GET_SOURCING_MANAGER'
export const GET_SOURCING_MANAGER_ERROR = 'GET_SOURCING_MANAGER_ERROR'