export const ADD_USERS = 'ADD_USERS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_USERS = 'GET_USERS';
export const REGISTER_ADD_USERS = 'REGISTER_ADD_USERS';
export const REGISTER_ADD_ERROR = 'REGISTER_ADD_ERROR';
export const USERS_ERROR = 'USERS_ERROR'
export const TOKEN_GENRATE = 'TOKEN_GENRATE'
export const USER_LIST = 'USER_LIST'
export const USER_DETAIL = 'USER_DETAIL'
export const USER_FILTERDETAIL = 'USER_FILTERDETAIL'
export const EDIT_USER = 'EDIT_USER'
export const USERSTATUS_UPDATE = 'USERSTATUS_UPDATE'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_ERROR = 'FORGOT_ERROR'
export const FORGOT_NULL = 'FORGOT_NULL'
export const OTPVERIFY = 'OTPVERIFY'
export const OTPVERIFY_NULL = 'OTPVERIFY_NULL'
export const OTPVERIFY_ERROR = 'OTPVERIFY_ERROR'
export const RESENDOTP = 'RESENDOTP'
export const RESENDOTP_NULL = 'RESENDOTP_NULL'
export const RESENDOTP_ERROR = 'RESENDOTP_ERROR'
export const UPDATEPASSWORD = 'UPDATEPASSWORD'
export const UPDATEPASSWORD_ERROR = 'UPDATEPASSWORD_ERROR'
export const UPDATEPASSWORD_NULL = 'UPDATEPASSWORD_NULL'
export const CHANGEPASSWORD = 'CHANGEPASSWORD'
export const CHANGEPASSWORD_ERROR = 'CHANGEPASSWORD_ERROR'
export const CHANGEPASSWORD_NULL = 'CHANGEPASSWORD_NULL'
export const USERREGISTER = 'USERREGISTER'
export const USERREGISTER_ERROR = 'USERREGISTER_ERROR'

// MASTER

export const GET_CITY_LIST = 'GET_CITY_LIST'
export const GET_CITY_LIST_ERROR = 'GET_CITY_LIST_ERROR'
export const GET_ROLE_LIST = 'GET_ROLE_LIST'
export const GET_ROLE_LIST_ERROR = 'GET_ROLE_LIST_ERROR'


// AGENCY

export const AGENCY_CREATE_FORM = 'AGENCY_CREATE_FORM'
export const AGENCY_CREATE_FORM_ERROR = 'AGENCY_CREATE_FORM_ERROR'
export const CREATE_AGENCY = 'CREATE_AGENCY'
export const CREATE_AGENCY_ERROR = 'CREATE_AGENCY_ERROR'

// SOURCUING TL

export const GET_SOURCINGMANAGER_LIST = 'GET_SOURCINGMANAGER_LIST'
export const GET_SOURCINGMANAGER_LIST_ERROR = 'GET_SOURCINGMANAGER_LIST_ERROR'