export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';


export const ADD_USERS = 'ADD_USERS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_USERS = 'GET_USERS';
export const REGISTER_ADD_USERS = 'REGISTER_ADD_USERS';
export const REGISTER_ADD_ERROR = 'REGISTER_ADD_ERROR';
export const USERS_ERROR = 'USERS_ERROR'
export const TOKEN_GENRATE = 'TOKEN_GENRATE'
export const USER_LIST = 'USER_LIST'
export const USER_DETAIL = 'USER_DETAIL'
export const USER_FILTERDETAIL = 'USER_FILTERDETAIL'
export const EDIT_USER = 'EDIT_USER'
export const USERSTATUS_UPDATE = 'USERSTATUS_UPDATE'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_ERROR = 'FORGOT_ERROR'
export const FORGOT_NULL = 'FORGOT_NULL'
export const OTPVERIFY = 'OTPVERIFY'
export const OTPVERIFY_NULL = 'OTPVERIFY_NULL'
export const OTPVERIFY_ERROR = 'OTPVERIFY_ERROR'
export const RESENDOTP = 'RESENDOTP'
export const RESENDOTP_NULL = 'RESENDOTP_NULL'
export const RESENDOTP_ERROR = 'RESENDOTP_ERROR'
export const UPDATEPASSWORD = 'UPDATEPASSWORD'
export const UPDATEPASSWORD_ERROR = 'UPDATEPASSWORD_ERROR'
export const UPDATEPASSWORD_NULL = 'UPDATEPASSWORD_NULL'
export const CHANGEPASSWORD = 'CHANGEPASSWORD'
export const CHANGEPASSWORD_ERROR = 'CHANGEPASSWORD_ERROR'
export const CHANGEPASSWORD_NULL = 'CHANGEPASSWORD_NULL'
export const USERREGISTER = 'USERREGISTER'
export const USERREGISTER_ERROR = 'USERREGISTER_ERROR'
export const REMOVE_USERDATA = 'REMOVE_USERDATA'

// MASTER

export const GET_CITY_LIST = 'GET_CITY_LIST'
export const GET_CITY_LIST_ERROR = 'GET_CITY_LIST_ERROR'
export const GET_ROLE_LIST = 'GET_ROLE_LIST'
export const GET_ROLE_LIST_ERROR = 'GET_ROLE_LIST_ERROR'


// AGENCY

export const AGENCY_CREATE_FORM = 'AGENCY_CREATE_FORM'
export const AGENCY_CREATE_FORM_ERROR = 'AGENCY_CREATE_FORM_ERROR'
export const CREATE_AGENCY = 'CREATE_AGENCY'
export const EDIT_AGENCY = 'EDIT_AGENCY'
export const CREATE_AGENCY_ERROR = 'CREATE_AGENCY_ERROR'
export const GET_AGENCY_DETAIL = 'GET_AGENCY_DETAIL'

// SOURCUING TL

export const GET_SOURCINGMANAGER_LIST = 'GET_SOURCINGMANAGER_LIST'
export const GET_SOURCINGMANAGER_LIST_ERROR = 'GET_SOURCINGMANAGER_LIST_ERROR'
export const GET_SOURCINGMANAGER_DETAIL = 'GET_SOURCINGMANAGER_DETAIL'
export const GET_SOURCINGMANAGER_DETAIL_ERROR = 'GET_SOURCINGMANAGER_DETAIL_ERROR'
export const GET_ASSIGNCP_LIST = 'GET_ASSIGNCP_LIST'
export const GET_ASSIGNCP_LIST_ERROR = 'GET_ASSIGNCP_LIST_ERROR'
export const ASSIGNCP_SM = 'ASSIGNCP_SM'
export const ASSIGNCP_SM_ERROR = 'ASSIGNCP_SM_ERROR'

// PROPERTY
export const PROPERTY_FORM = 'PROPERTY_FORM'
export const PROPERTY_FORM_UPDATE = 'PROPERTY_FORM_UPDATE'
export const ADD_PROPERTY = 'ADD_PROPERTY'
export const PROPERTY_LIST = 'PROPERTY_LIST'
export const PROPERTY_EDIT = 'PROPERTY_EDIT'
export const GETPROPERTY_DETAIL = 'GETPROPERTY_DETAIL'
export const PROPERTY_FILTER_LIST = 'PROPERTY_FILTER_LIST'
export const PROPERTY_STATUS_UPDATE = 'PROPERTY_STATUS_UPDATE'
export const PROPERTY_ERROR = 'PROPERTY_ERROR'
export const SOURCING_MANAGER_LIST = 'SOURCING_MANAGER_LIST'
export const ALLOCATE_PROPERTY_TO_USER = 'ALLOCATE_PROPERTY_TO_USER'


// Leads
export const VISITOR_LIST = 'VISITOR_LIST'
export const VISITOR_ERROR = 'VISITOR_ERROR'
export const ADD_VISITOR = 'ADD_VISITOR'
export const EDIT_VISITOR = 'EDIT_VISITOR'
export const GET_VISITOR_DETAIL = 'GET_VISITOR_DETAIL'
export const VISITOR_STATUSUPDATE = 'VISITOR_STATUSUPDATE'
export const ADD_VISITOR_FORM = 'ADD_VISITOR_FORM'
export const REMOVE_VISITOR = 'REMOVE_VISITOR'
export const GET_USERVISIT_LIST = 'GET_USERVISIT_LIST'
export const GET_USERVISIT_LIST_ERROR = 'GET_USERVISIT_LIST_ERROR'

// MASTER
export const CREATE_MASTER = 'CREATE_MASTER'
export const GET_AMENITY = 'GET_AMENITY'
export const GET_CONFIGURATION = 'GET_CONFIGURATION'
export const GET_PROPERTY_TYPE = 'GET_PROPERTY_TYPE'
export const GET_INSENTIVE_TYPE = 'GET_INSENTIVE_TYPE'
export const MASTER_LIST = 'MASTER_LIST'
export const MASTER_ERROR = 'MASTER_ERROR'
export const GET_SOURCING_MANAGER = 'GET_SOURCING_MANAGER'
export const GET_SOURCING_MANAGER_ERROR = 'GET_SOURCING_MANAGER_ERROR'

// AGENT
export const AGENT_LIST = 'AGENCY_LIST'
export const AGENT_ERROR = 'AGENCY_ERROR'
export const ADD_AGENT = 'ADD_AGENT'
export const EDIT_AGENT = 'EDIT_AGENT'
export const GET_AGENT_DETAIL = 'GET_AGENT_DETAIL'
export const AGENT_STATUSUPDATE = 'AGENT_STATUSUPDATE'
export const ADD_AGENT_FORM = 'ADD_AGENT_FORM'

// APPOINTMENT
export const GET_APPOINTMENT_LIST = 'GET_APPOINTMENT_LIST'
export const GET_APPOINTMENT_LIST_ERROR = 'GET_APPOINTMENT_LIST_ERROR'
export const GET_APPOINTMENT_DETAILS = 'GET_APPOINTMENT_DETAILS'
export const GET_APPOINTMENT_DETAILS_ERROR = 'GET_APPOINTMENT_DETAILS_ERROR'
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'
export const ADD_APPOINTMENT_ERROR = 'ADD_APPOINTMENT_ERROR'
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT'
export const EDIT_APPOINTMENT_ERROR = 'EDIT_APPOINTMENT_ERROR'
export const ADD_DROPLOCATION = 'ADD_DROPLOCATION'
export const ADD_DROPLOCATION_ERROR = 'ADD_DROPLOCATION_ERROR'
export const ALLOCATE_CM_APPOINTMENT = 'ALLOCATE_CM_APPOINTMENT'
export const ALLOCATE_CM_APPOINTMENT_ERROR = 'ALLOCATE_CM_APPOINTMENT_ERROR'

// BOOKING
export const ADD_BOOKING = 'ADD_BOOKING'
export const ADD_BOOKING_ERROR = 'ADD_BOOKING_ERROR'

// Update setting

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_ERROR = 'ADD_VISITOR_FORM'

// FOLLOWUP START
export const GET_FOLLOWUP_LIST = 'GET_FOLLOWUP'
export const FOLLOWUP_ERROR = 'FOLLOWUP_ERROR'
export const FOLLOWUP_DETAILS = 'FOLLOWUP_DETAILS'
export const FOLLOWUP_DETAILS_ERROR = 'FOLLOWUP_DETAILS_ERROR'
export const UPDATE_FOLLOWUP = 'UPDATE_FOLLOWUP'
export const UPDATE_FOLLOWUP_ERROR = 'UPDATE_FOLLOWUP_ERROR'
export const REMOVE_FOLLOWUP_DATA = 'REMOVE_FOLLOWUP_DATA'
export const ADD_FOLLOWUP = 'ADD_FOLLOWUP'
export const ADD_FOLLOWUP_ERROR = 'ADD_FOLLOWUP_ERROR'

//
export const GET_CLOSINGMANAGER_LIST = 'GET_CLOSINGMANAGER_LIST'
export const GET_CLOSINGMANAGER_LIST_ERROR = 'GET_CLOSINGMANAGER_LIST_ERROR'
export const GET_CLOSINGMANAGER_DETAIL = 'GET_CLOSINGMANAGER_DETAIL'
export const GET_CLOSINGMANAGER_DETAIL_ERROR = 'GET_CLOSINGMANAGER_DETAIL_ERROR'
